#!/usr/bin/env bash
set -euo pipefail

APP="Proxmox Share Autostarter"
RAW_BASE="${RAW_BASE:-https://raw.githubusercontent.com/D35P4C1T0/proxmox-smb-container-autostarter/main}"
INSTALL_ROOT="${INSTALL_ROOT:-}"
SOURCE_DIR="${SOURCE_DIR:-$(cd "$(dirname "$0")" 2>/dev/null && pwd || true)}"
CONFIG_PATH="${INSTALL_ROOT}/etc/share-autostart.conf"
CREDENTIALS_PATH="${INSTALL_ROOT}/root/.smbcredentials"

YW='\033[33m'; GN='\033[1;92m'; RD='\033[01;31m'; CL='\033[m'
ok() { printf "${GN}✓${CL} %s\n" "$*"; }
info() { printf "${YW}▶${CL} %s\n" "$*"; }
fail() { printf "${RD}✗${CL} %s\n" "$*" >&2; exit 1; }

header() {
    clear 2>/dev/null || true
    cat <<'EOF'
  ___  _                 _         _         _             _
 / __|| |_  __ _  _ _  | |__ ___ | |_  ___| |_  __ _  _ | |_
 \__ \| ' \/ _` || '_| | / // -_)|  _|/ _ \  _|/ _` || ||  _|
 |___/|_||_\__,_||_|   |_\_\\___| \__|\___/\__|\__,_| \__\__|
EOF
    printf '\n%s\n\n' "$APP"
}

ask_input() {
    local title=$1 prompt=$2 default=${3:-} value
    if command -v whiptail >/dev/null 2>&1; then
        value=$(whiptail --title "$title" --inputbox "$prompt" 10 72 "$default" 3>&1 1>&2 2>&3) || exit 0
    else
        read -rp "$prompt [$default]: " value </dev/tty
        value=${value:-$default}
    fi
    printf '%s' "$value"
}

ask_password() {
    local prompt=$1 value
    if command -v whiptail >/dev/null 2>&1; then
        value=$(whiptail --title "$APP" --passwordbox "$prompt" 10 72 3>&1 1>&2 2>&3) || exit 0
    else
        read -rsp "$prompt: " value </dev/tty
        printf '\n' >/dev/tty
    fi
    printf '%s' "$value"
}

ask_menu() {
    local prompt=$1
    shift
    if command -v whiptail >/dev/null 2>&1; then
        whiptail --title "$APP" --menu "$prompt" 14 72 6 "$@" 3>&1 1>&2 2>&3 || exit 0
    else
        local index=1 item
        printf '%s\n' "$prompt" >/dev/tty
        while (( $# )); do
            printf '  %s) %s - %s\n' "$index" "$1" "$2" >/dev/tty
            shift 2
            index=$((index + 1))
        done
        read -rp 'Choice [1]: ' item </dev/tty
        printf '%s' "${item:-1}"
    fi
}

confirm() {
    local prompt=$1
    if command -v whiptail >/dev/null 2>&1; then
        whiptail --title "$APP" --yesno "$prompt" 10 72
    else
        local answer
        read -rp "$prompt [Y/n]: " answer </dev/tty
        [[ ! "$answer" =~ ^[Nn]$ ]]
    fi
}

write_config() {
    install -d -m 0755 "$(dirname "$CONFIG_PATH")"
    {
        printf '# Generated by Proxmox Share Autostarter installer\n'
        printf 'PROTOCOL=%q\n' "$PROTOCOL"
        printf 'SHARE_HOST=%q\n' "$SHARE_HOST"
        printf 'SHARE_NAME=%q\n' "$SHARE_NAME"
        printf 'TAG=%q\n' "$TAG"
        printf 'SOURCE_VMID=%q\n' "$SOURCE_VMID"
        printf 'SOURCE_TYPE=%q\n' "$SOURCE_TYPE"
        printf 'CREDENTIALS_FILE=%q\n' "$CREDENTIALS_FILE"
        printf 'MAX_WAIT=%q\n' "$MAX_WAIT"
        printf 'SLEEP_INTERVAL=5\nSTART_TIMEOUT=60\nLOG_FILE=\n'
    } > "$CONFIG_PATH"
    chmod 0600 "$CONFIG_PATH"
}

configure() {
    PROTOCOL=$(ask_menu "Choose share protocol" smb "SMB/CIFS (recommended)" nfs "NFS export")
    [[ "$PROTOCOL" == 1 ]] && PROTOCOL=smb
    [[ "$PROTOCOL" == 2 ]] && PROTOCOL=nfs
    SHARE_HOST=$(ask_input "$APP" "NAS hostname or IP address" "${SHARE_HOST:-192.168.1.100}")
    if [[ "$PROTOCOL" == smb ]]; then
        SHARE_NAME=$(ask_input "$APP" "SMB share name (not //host/share)" "${SHARE_NAME:-media}")
    else
        SHARE_NAME=$(ask_input "$APP" "Exact NFS export path" "${SHARE_NAME:-/mnt/tank/media}")
    fi
    TAG=$(ask_input "$APP" "Exact LXC tag to manage" "${TAG:-smb}")
    SOURCE_VMID=$(ask_input "$APP" "NAS VM/LXC ID; leave empty for external NAS" "${SOURCE_VMID:-}")
    SOURCE_TYPE=qemu
    if [[ -n "$SOURCE_VMID" ]]; then
        SOURCE_TYPE=$(ask_menu "NAS guest type" qemu "Virtual machine" lxc "LXC container")
        [[ "$SOURCE_TYPE" == 1 ]] && SOURCE_TYPE=qemu
        [[ "$SOURCE_TYPE" == 2 ]] && SOURCE_TYPE=lxc
    fi
    MAX_WAIT=$(ask_input "$APP" "Seconds to wait per attempt" "${MAX_WAIT:-600}")

    CREDENTIALS_FILE=""
    SMB_USERNAME=""
    SMB_PASSWORD=""
    if [[ "$PROTOCOL" == smb ]]; then
        SMB_USERNAME=$(ask_input "$APP" "SMB username; leave empty for guest access" "")
        if [[ -n "$SMB_USERNAME" ]]; then
            SMB_PASSWORD=$(ask_password "SMB password for $SMB_USERNAME")
            CREDENTIALS_FILE="/root/.smbcredentials"
        fi
    fi

    [[ -n "$SHARE_HOST" && -n "$SHARE_NAME" && -n "$TAG" ]] || fail "Host, share, and tag are required"
    [[ "$SOURCE_VMID" =~ ^[0-9]*$ ]] || fail "Guest ID must be numeric"
    [[ "$MAX_WAIT" =~ ^[0-9]+$ ]] || fail "Wait time must be numeric"
    [[ "$SMB_USERNAME" != *$'\n'* && "$SMB_USERNAME" != *$'\r'* && \
        "$SMB_PASSWORD" != *$'\n'* && "$SMB_PASSWORD" != *$'\r'* ]] || \
        fail "SMB username and password cannot contain line breaks"

    local summary="Protocol: ${PROTOCOL^^}\nShare: ${SHARE_HOST}:${SHARE_NAME}\nTag: ${TAG}\nProvider guest: ${SOURCE_VMID:-external NAS}\nWait: ${MAX_WAIT}s"
    confirm "$summary\n\nInstall with these settings?" || exit 0
}

fetch() {
    local path=$1 output=$2
    if [[ -n "$SOURCE_DIR" && -f "$SOURCE_DIR/$path" ]]; then
        cp "$SOURCE_DIR/$path" "$output"
    else
        curl -fsSL "$RAW_BASE/$path" -o "$output"
    fi
}

[[ $EUID -eq 0 ]] || fail "Run installer as root"
command -v pct >/dev/null 2>&1 || fail "This is not a Proxmox VE node (pct missing)"

header

if [[ -z "$INSTALL_ROOT" ]] && ! pveversion | grep -Eq 'pve-manager/(8\.[0-9]+|9\.[0-9]+)'; then
    fail "Supported Proxmox VE versions: 8.x and 9.x"
fi

# Preserve and understand prior configuration before offering reconfiguration.
if [[ ! -e "$CONFIG_PATH" && -e "${INSTALL_ROOT}/etc/smb-autostart.conf" ]]; then
    install -m 0600 "${INSTALL_ROOT}/etc/smb-autostart.conf" "$CONFIG_PATH"
    ok "Migrated /etc/smb-autostart.conf"
fi

RECONFIGURE=1
if [[ -e "$CONFIG_PATH" ]]; then
    # shellcheck source=/dev/null
    source "$CONFIG_PATH"
    if [[ "${NONINTERACTIVE:-0}" == 1 ]]; then
        RECONFIGURE=0
    elif ! confirm "Existing configuration found. Reconfigure it?\n\nChoose No to update program files only."; then
        RECONFIGURE=0
    fi
fi

if [[ "${NONINTERACTIVE:-0}" != 1 && $RECONFIGURE == 1 ]]; then
    configure
    write_config
elif [[ ! -e "$CONFIG_PATH" ]]; then
    fail "Noninteractive install requires existing $CONFIG_PATH"
fi

PROTOCOL="${PROTOCOL:-smb}"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
info "Downloading program files"
fetch src/start-smb-containers.sh "$tmp/autostart"
fetch systemd/share-autostart.service "$tmp/service"

install -d -m 0755 "${INSTALL_ROOT}/usr/local/sbin" "${INSTALL_ROOT}/etc/systemd/system"
install -m 0755 "$tmp/autostart" "${INSTALL_ROOT}/usr/local/sbin/proxmox-share-autostart"
install -m 0644 "$tmp/service" "${INSTALL_ROOT}/etc/systemd/system/share-autostart.service"
ok "Installed program and systemd service"

if [[ "${PROTOCOL:-smb}" == smb && -n "${SMB_USERNAME:-}" ]]; then
    install -d -m 0700 "$(dirname "$CREDENTIALS_PATH")"
    { printf 'username=%s\n' "$SMB_USERNAME"; printf 'password=%s\n' "$SMB_PASSWORD"; } > "$CREDENTIALS_PATH"
    chmod 0600 "$CREDENTIALS_PATH"
    ok "Stored SMB credentials with mode 0600"
fi

if [[ -z "$INSTALL_ROOT" ]]; then
    info "Installing ${PROTOCOL^^} client dependency"
    apt-get update -qq
    if [[ "$PROTOCOL" == nfs ]]; then apt-get install -y -qq nfs-common; else apt-get install -y -qq smbclient; fi
    systemctl daemon-reload
    systemctl enable -q share-autostart.service
    systemctl start --no-block share-autostart.service
    ok "Enabled share-autostart.service; startup check is running"
fi

printf "\n${GN}%s installation complete${CL}\n" "$APP"
printf 'Configuration: /etc/share-autostart.conf\n'
printf 'Logs: journalctl -u share-autostart.service -f\n'
