/var/log/smb-autostart.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    create 0644 root root
    sharedscripts
    postrotate
        systemctl reload start-smb-containers.service > /dev/null 2>&1 || true
    endscript
}

